apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: saatvik-app
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-app-container
          image: 'user-app-service:1.0'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9191
