apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  namespace: saatvik-app
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  type: NodePort